language: erlang
otp_release:
  - 19.3
  - 20.2
  - 21.1

env:
  - EMACS_VERSION=24.3
  - EMACS_VERSION=25.3
  - EMACS_VERSION=26.1
  
sudo: required

cache:
  - directories:
      - "$HOME/emacs/"

matrix:
  fast_finish: true

before_script:
  # Configure $PATH: Executables are installed to $HOME/bin
  - export PATH="$HOME/bin:$PATH"
  # Download the makefile to emacs-travis.mk
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  # Install Emacs (according to $EMACS_VERSION) and Cask
  - make -f emacs-travis.mk install_emacs
  - make -f emacs-travis.mk install_cask
  # Install Texinfo, if you need to build info manuals for your project
  - make -f emacs-travis.mk install_texinfo
  - curl -O -L https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3
  - ./rebar3 update
  
script:
  - make && ./rebar3 compile
  
